language: node_js

node_js:
  - stable
  - "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.14.0
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

script:
  - yarn test
  - yarn lint

after_success:
  - yarn coveralls
